-- English localization for all database and custom-interface text.
INSERT OR REPLACE INTO Language_en_US (Tag, Text) VALUES
('TXT_KEY_CIV_PPB_DESC', 'The Possession Browsers'),
('TXT_KEY_CIV_PPB_SHORT_DESC', 'Possession Browsers'),
('TXT_KEY_CIV_PPB_ADJECTIVE', 'Browser'),
('TXT_KEY_CIV_PPB_PEDIA', 'The Possession Browsers built their realm from watched frames, saved clips, long comments, and an alarming willingness to treat enemy bodies as temporary accounts. Under Trentrouls, curiosity becomes logistics: every fictional creator post may become a battlefield possession.'),
('TXT_KEY_CIV_PPB_STRATEGY', 'Build a bank of Saved Clips before major wars. Possession Theory reaches distant targets, Body-Hop extends a successful attack, and Main Host clips turn a carefully selected enemy unit into a permanent investment. Great Writers and the Premium Subscription accelerate the feed.'),
('TXT_KEY_CIV5_PPB_POSSESSION_BROWSERS_HEADING_1', 'Origins'),
('TXT_KEY_CIV5_PPB_POSSESSION_BROWSERS_TEXT_1', 'Una Court became the capital of a nation whose archives were equal parts criticism, speculation, sequel request, and tactical doctrine.'),
('TXT_KEY_CIV5_DAWN_PPB_TEXT', 'O Trentrouls, your people have perfected the art of watching far too closely. ParasiteLovers posts; you comment; the best moments become Saved Clips, and enemy soldiers discover that ownership is more negotiable than they expected. Choose a Main Host wisely, evolve it carefully, and let every new notification become someone else''s military problem. Will your feed refresh forever?'),

('TXT_KEY_LEADER_PPB_TRENTROULS', 'Trentrouls'),
('TXT_KEY_LEADER_PPB_TRENTROULS_PEDIA', 'Trentrouls is an obsessive browser, prolific commenter, and reluctant military theorist whose preferred solution to an enemy army is to borrow its best member.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_PPB_TRENTROULS_HEADING_1', 'The Browser of Una Court'),
('TXT_KEY_CIVILOPEDIA_LEADERS_PPB_TRENTROULS_TEXT_1', 'Trentrouls follows every arc, studies every glowing eye, and develops strong opinions about which host should remain important. In war, those opinions become remarkably literal.'),

('TXT_KEY_TRAIT_PPB_FAN_SHORT', 'I''m a Fan of More Baby Content!'),
('TXT_KEY_TRAIT_PPB_FAN_HELP', 'Browse a fictional creator feed that publishes every 12 turns on Standard Speed. Comment once per post to save a possession Clip (maximum 3). Spend Clips to possess visible wartime enemy combat units near your military or Cities. Maintain one temporary Side Host and one permanent, evolvable Main Host. The feed is entirely offline.'),

('TXT_KEY_UNIT_PPB_PATREON_REGULAR', 'Patreon Regular'),
('TXT_KEY_UNIT_PPB_PATREON_REGULAR_HELP', 'Unique Great Writer. May Create a Great Work. In the Patreon interface it can instead Leave an Essay-Length Comment: generate a bonus post, gain Culture, and make the selected comment award two matching Saved Clips. It cannot write a Political Treatise.'),
('TXT_KEY_UNIT_PPB_PATREON_REGULAR_STRATEGY', 'Keep two Clip slots free before using Leave an Essay-Length Comment. The resulting post awards two Clips when answered, making Patreon Regulars exceptionally valuable before war.'),
('TXT_KEY_UNIT_PPB_PATREON_REGULAR_PEDIA', 'A Patreon Regular is ready with an essay before anyone has asked a question. The unit retains Create Great Work, but its Political Treatise is replaced in practice by an action in Trentrouls'' fictional creator feed.'),

('TXT_KEY_BUILDING_PPB_PREMIUM_SUBSCRIPTION', 'Premium Subscription'),
('TXT_KEY_BUILDING_PPB_PREMIUM_SUBSCRIPTION_HELP', 'Replaces the National Epic and retains its normal benefits. The fictional creator feed refreshes every 9 turns instead of 12 on Standard Speed, Saved Clip capacity increases from 3 to 4, and this City produces +2 Great Writer Points per turn.'),
('TXT_KEY_BUILDING_PPB_PREMIUM_SUBSCRIPTION_STRATEGY', 'The Premium Subscription accelerates the entire civilization mechanic and gives Patreon Regulars a direct generation boost. Build it before a long campaign so more posts arrive while units are in range.'),
('TXT_KEY_BUILDING_PPB_PREMIUM_SUBSCRIPTION_PEDIA', 'At some point checking the page this often becomes a subscription tier. The Premium Subscription is mechanically the National Epic with a faster feed, a larger Clip library, and direct Great Writer generation.'),

('TXT_KEY_PROMOTION_PPB_TEMP_HOST', 'Temporary Host'),
('TXT_KEY_PROMOTION_PPB_TEMP_HOST_HELP', 'This unit is temporarily controlled by Trentrouls and will return to its previous owner when the possession expires or peace is made. It cannot be gifted, disbanded, or upgraded.'),
('TXT_KEY_PROMOTION_PPB_BODY_HOP_HOST', 'Body-Hop Ready'),
('TXT_KEY_PROMOTION_PPB_BODY_HOP_HOST_HELP', 'After this host destroys an eligible enemy unit, Trentrouls may move into the defeated unit type once. The old body returns immediately.'),
('TXT_KEY_PROMOTION_PPB_MAIN_HOST', 'Main Host'),
('TXT_KEY_PROMOTION_PPB_MAIN_HOST_HELP', '+10% Combat Strength. Permanently controlled by Trentrouls until death or release. Cannot be captured, gifted, disbanded, or upgraded.'),
('TXT_KEY_PROMOTION_PPB_EVOLUTION_1', 'Main Host: Evolution I'),
('TXT_KEY_PROMOTION_PPB_EVOLUTION_1_HELP', '+5% Combat Strength. This Evolution is lost when the Main Host is released or dies.'),
('TXT_KEY_PROMOTION_PPB_EVOLUTION_2', 'Main Host: Evolution II'),
('TXT_KEY_PROMOTION_PPB_EVOLUTION_2_HELP', '+10% Combat Strength. This Evolution is lost when the Main Host is released or dies.'),
('TXT_KEY_PROMOTION_PPB_EVOLUTION_3', 'Main Host: Evolution III'),
('TXT_KEY_PROMOTION_PPB_EVOLUTION_3_HELP', '+15% Combat Strength. This Evolution is lost when the Main Host is released or dies.'),
('TXT_KEY_PROMOTION_PPB_DEFENDING_POST', 'Defending the Post'),
('TXT_KEY_PROMOTION_PPB_DEFENDING_POST_HELP', '+15% Combat Strength while defending and heals 10 HP after destroying an enemy unit.'),

('TXT_KEY_CITY_NAME_PPB_UNA_COURT', 'Una Court'),
('TXT_KEY_CITY_NAME_PPB_CREATOR_HUB', 'Creator Hub'),
('TXT_KEY_CITY_NAME_PPB_SAVED_FOLDER', 'Saved Folder'),
('TXT_KEY_CITY_NAME_PPB_MAIN_HOST', 'Main Host'),
('TXT_KEY_CITY_NAME_PPB_GLOWING_EYES', 'Glowing Eyes'),
('TXT_KEY_CITY_NAME_PPB_COMMENT_CHAIN', 'Comment Chain'),
('TXT_KEY_CITY_NAME_PPB_PART_TWO', 'Part Two'),
('TXT_KEY_CITY_NAME_PPB_FEED_REFRESH', 'Feed Refresh'),
('TXT_KEY_CITY_NAME_PPB_PARASITE_LOVERS', 'ParasiteLovers'),
('TXT_KEY_CITY_NAME_PPB_BODY_HOP', 'Body Hop'),
('TXT_KEY_CITY_NAME_PPB_PREFERRED_BODY', 'Preferred Body'),
('TXT_KEY_CITY_NAME_PPB_PREMIUM_TIER', 'Premium Tier'),
('TXT_KEY_CITY_NAME_PPB_LONG_COMMENT', 'Long Comment'),
('TXT_KEY_CITY_NAME_PPB_FRAME_BY_FRAME', 'Frame by Frame'),
('TXT_KEY_CITY_NAME_PPB_NEW_NOTIFICATION', 'New Notification'),
('TXT_KEY_SPY_NAME_PPB_0', 'FrameScrubber'),
('TXT_KEY_SPY_NAME_PPB_1', 'CommentWatcher'),
('TXT_KEY_SPY_NAME_PPB_2', 'ClipKeeper'),
('TXT_KEY_SPY_NAME_PPB_3', 'HostTracker'),
('TXT_KEY_SPY_NAME_PPB_4', 'PartThree'),
('TXT_KEY_SPY_NAME_PPB_5', 'EyeLine'),
('TXT_KEY_SPY_NAME_PPB_6', 'TierUp'),
('TXT_KEY_SPY_NAME_PPB_7', 'MainBody'),

('TXT_KEY_PPB_CLIP_MORE', 'More Baby Clip'),
('TXT_KEY_PPB_CLIP_MORE_HELP', 'Possession lasts one additional Standard-Speed turn.'),
('TXT_KEY_PPB_CLIP_THEORY', 'Possession Theory Clip'),
('TXT_KEY_PPB_CLIP_THEORY_HELP', 'Target eligible hosts within 7 tiles instead of 4 and reveal detailed unit information.'),
('TXT_KEY_PPB_CLIP_BODY_HOP', 'Body-Hop Clip'),
('TXT_KEY_PPB_CLIP_BODY_HOP_HELP', 'After the host kills an eligible enemy, it may move into the defeated unit type once and gain possession time.'),
('TXT_KEY_PPB_CLIP_MAIN_HOST', 'Main Host Clip'),
('TXT_KEY_PPB_CLIP_MAIN_HOST_HELP', 'Use as a normal Clip, combine with one other Clip to establish a Main Host, or consume it to evolve an existing Main Host.'),
('TXT_KEY_PPB_CLIP_LOYAL', 'Loyal Patron Clip'),
('TXT_KEY_PPB_CLIP_LOYAL_HELP', 'The possessed host gains Defending the Post: +15% defense and heals 10 HP after a kill.'),

('TXT_KEY_PPB_UI_BUTTON', 'PATREON'),
('TXT_KEY_PPB_UI_TITLE', 'PARASITELOVERS'),
('TXT_KEY_PPB_UI_SUBTITLE', 'Creating possession animations, transformations and questionable amounts of glowing eyes.'),
('TXT_KEY_PPB_UI_FEED_TAB', 'CREATOR FEED'),
('TXT_KEY_PPB_UI_CLIPS_TAB', 'SAVED CLIPS'),
('TXT_KEY_PPB_UI_HOST_TAB', 'MAIN HOST'),
('TXT_KEY_PPB_UI_TARGET_HEADER', 'AVAILABLE HOSTS'),
('TXT_KEY_PPB_UI_CLOSE', 'Close'),
('TXT_KEY_PPB_UI_REFRESH', 'Refresh'),
('TXT_KEY_PPB_UI_POST_META', 'Turn {1}  |  [ICON_HAPPINESS_1] {2} likes  |  [ICON_TRADE] {3} comments'),
('TXT_KEY_PPB_UI_COMMENTED', 'Trentrouls commented: “{1}”'),
('TXT_KEY_PPB_UI_CLIP_FULL', 'Clip storage is full. Spend a Clip before commenting.'),
('TXT_KEY_PPB_UI_ESSAY', 'Leave an Essay-Length Comment'),
('TXT_KEY_PPB_UI_ESSAY_NEEDS_SPACE', 'Two empty Clip slots are required because the bonus post awards two Clips.'),
('TXT_KEY_PPB_UI_ESSAY_NONE', 'No Patreon Regular is available.'),
('TXT_KEY_PPB_UI_CLIP_HEADER', 'Saved Clips: {1}/{2}'),
('TXT_KEY_PPB_UI_NO_CLIPS', 'No Saved Clips. Comment on a creator post first.'),
('TXT_KEY_PPB_UI_USE_CLIP', 'Select'),
('TXT_KEY_PPB_UI_SELECTED', 'Selected'),
('TXT_KEY_PPB_UI_CLIP_SOURCE', 'Saved from post {1} on turn {2}.'),
('TXT_KEY_PPB_UI_SELECT_CLIP_FIRST', 'Select a Saved Clip to browse eligible hosts.'),
('TXT_KEY_PPB_UI_POSSESS', 'Possess'),
('TXT_KEY_PPB_UI_MAKE_MAIN', 'Make Main Host'),
('TXT_KEY_PPB_UI_REPLACE_MAIN', 'Replace Main Host'),
('TXT_KEY_PPB_UI_NO_TARGETS', 'No eligible visible wartime hosts are in range. Targets in Cities, stacked with another unit, carrying cargo, or belonging to Barbarians are excluded for transfer safety.'),
('TXT_KEY_PPB_UI_TARGET_BASIC', '{1} — {2}[NEWLINE][ICON_STRENGTH] {3}  |  Distance {4}'),
('TXT_KEY_PPB_UI_TARGET_THEORY', '{1} — {2}[NEWLINE][ICON_STRENGTH] {3}  |  HP {4}/100  |  Moves {5}[NEWLINE]XP {6}  |  Promotions {7}  |  Distance {8}'),
('TXT_KEY_PPB_UI_MAIN_NONE', 'No Main Host is currently established.'),
('TXT_KEY_PPB_UI_MAIN_STATUS', '{1}[NEWLINE]Original owner: {2}[NEWLINE]Evolution {3}/3[NEWLINE]Total Main Host combat bonus: +{4}%'),
('TXT_KEY_PPB_UI_EVOLVE', 'Evolve Main Host'),
('TXT_KEY_PPB_UI_EVOLVE_NO_CLIP', 'A Main Host Clip is required.'),
('TXT_KEY_PPB_UI_EVOLVE_MAX', 'This Main Host has reached maximum Evolution.'),
('TXT_KEY_PPB_UI_RELEASE', 'Release Main Host'),
('TXT_KEY_PPB_UI_UNKNOWN_OWNER', 'unknown'),
('TXT_KEY_PPB_UI_UNKNOWN_HOST', 'unknown host'),
('TXT_KEY_PPB_UI_TEMP_STATUS', 'Side Host: {1} ({2} turns remaining)'),
('TXT_KEY_PPB_UI_TEMP_NONE', 'Side Host: none'),
('TXT_KEY_PPB_UI_NEXT_POST', 'Next regular post in {1} turn(s).'),
('TXT_KEY_PPB_UI_BODY_HOP_TITLE', 'BABY IS MOVING BODIES'),
('TXT_KEY_PPB_UI_BODY_HOP_TEXT', 'Current Body: {1}[NEWLINE]New Body: {2}[NEWLINE][NEWLINE]Changing bodies returns the current host, creates the new host at 50 HP, transfers the remaining duration, and adds time.'),
('TXT_KEY_PPB_UI_BODY_HOP_STAY', 'Stay in Current Body'),
('TXT_KEY_PPB_UI_BODY_HOP_ACCEPT', 'Possess New Body'),

('TXT_KEY_PPB_NOTIFICATION_NEW_POST_TITLE', 'New ParasiteLovers Post'),
('TXT_KEY_PPB_NOTIFICATION_NEW_POST_BODY', 'ParasiteLovers posted: “{1}”. Open PATREON to comment.'),
('TXT_KEY_PPB_LOYAL_REWARD', 'Defending the creator grants {1} Culture and {2} Golden Age Points.'),
('TXT_KEY_PPB_ESSAY_REWARD', 'The essay generates a bonus post and {1} Culture. Its selected comment will award two matching Clips.'),
('TXT_KEY_PPB_ALERT_TEMP_STARTED', '{1} is possessed for {2} turn(s).'),
('TXT_KEY_PPB_ALERT_TEMP_ENDED', 'Temporary possession ended: {1}.'),
('TXT_KEY_PPB_ALERT_TEMP_KILLED', 'The temporary host was destroyed. Nothing returns to its previous owner.'),
('TXT_KEY_PPB_ALERT_MAIN_ESTABLISHED', '{1} is now Trentrouls'' Main Host.'),
('TXT_KEY_PPB_ALERT_MAIN_EVOLVED', '{1} reached Main Host Evolution {2}.'),
('TXT_KEY_PPB_ALERT_MAIN_RELEASED', 'The Main Host was released: {1}.'),
('TXT_KEY_PPB_ALERT_MAIN_KILLED', 'The Main Host was destroyed. All Evolution was lost.'),
('TXT_KEY_PPB_ALERT_BODY_HOP', 'Body-Hop complete: {1} rises at 50 HP with {2} turn(s) remaining.'),
('TXT_KEY_PPB_REASON_PEACE', 'peace was made'),
('TXT_KEY_PPB_REASON_EXPIRED', 'the Clip duration expired'),
('TXT_KEY_PPB_REASON_VOLUNTARY', 'released voluntarily'),
('TXT_KEY_PPB_REASON_NEW_MAIN', 'a new Main Host was selected'),

('TXT_KEY_LEADER_PPB_FIRSTGREETING_1', 'You found the page. Good. There is a lot of context, but I have saved the important parts.'),
('TXT_KEY_LEADER_PPB_GREETING_POLITE_1', 'A new post just appeared. We can talk while I read it.'),
('TXT_KEY_LEADER_PPB_GREETING_NEUTRAL_1', 'What did you want to discuss?'),
('TXT_KEY_LEADER_PPB_GREETING_HOSTILE_1', 'You seem to always be disappointed. Perhaps this page is not for you.'),
('TXT_KEY_LEADER_PPB_LETSHEARIT_1', 'Go on.'),
('TXT_KEY_LEADER_PPB_DECLAREWAR_1', 'I have studied your strongest units frame by frame. One of them is about to become the main body.'),
('TXT_KEY_LEADER_PPB_ATTACKED_1', 'A hostile comment, then. I will answer it properly.'),
('TXT_KEY_LEADER_PPB_DEFEATED_1', 'The feed is empty. Even the saved folder is gone.'),
('TXT_KEY_LEADER_PPB_TRADE_YES_1', 'That works. Saved.'),
('TXT_KEY_LEADER_PPB_TRADE_NO_1', 'No. The value is not there.'),
('TXT_KEY_LEADER_PPB_PEACE_1', 'Fine. The side host goes back. The Main Host stays.'),
('TXT_KEY_LEADER_PPB_DEMAND_1', 'You should probably send that before the next part arrives.'),

('TXT_KEY_PPB_POST_01_TITLE', 'Something Behind the Eyes — Part I'),
('TXT_KEY_PPB_POST_01_TEXT', 'A quiet first look at Baby''s newest host. The eyes only change for a few frames, but that may be the most important part.'),
('TXT_KEY_PPB_POST_02_TITLE', 'Moving Bodies — Part II'),
('TXT_KEY_PPB_POST_02_TEXT', 'Baby does not seem interested in staying in one body. Watch the lines passing through the eyes during the transition.'),
('TXT_KEY_PPB_POST_03_TITLE', 'The Preferred Host — Part III'),
('TXT_KEY_PPB_POST_03_TEXT', 'There are several hosts now, but one is becoming more important. Part IV will develop that relationship.'),
('TXT_KEY_PPB_POST_04_TITLE', 'Host Evolution — Part IV'),
('TXT_KEY_PPB_POST_04_TEXT', 'The parasite and host are beginning to change together. The next animation should make the evolution much more visible.'),
('TXT_KEY_PPB_POST_05_TITLE', 'Possession at the Pool'),
('TXT_KEY_PPB_POST_05_TEXT', 'A short side scene became a full sequence after the new host tried to interrupt. It is now considerably less clear who is interrupting whom.'),
('TXT_KEY_PPB_POST_06_TITLE', 'Everyone Gets Glowing Eyes'),
('TXT_KEY_PPB_POST_06_TEXT', 'Testing several variations of the possession effect. The timing is different on every character, but the eye lines remain consistent.'),
('TXT_KEY_PPB_POST_07_TITLE', 'The Comments Section Is Also a Battlefield'),
('TXT_KEY_PPB_POST_07_TEXT', 'Work continues on the next part. Preview frames are attached while the transition animation is cleaned up.'),
('TXT_KEY_PPB_POST_07_NEGATIVE', 'RandomPatron92: “Honestly this one was disappointing again.”'),
('TXT_KEY_PPB_POST_08_TITLE', 'New Host, Same Parasite'),
('TXT_KEY_PPB_POST_08_TEXT', 'Baby finds a stronger body, but the previous host is still present in the scene. That will matter later.'),
('TXT_KEY_PPB_POST_09_TITLE', 'Behind the Animation'),
('TXT_KEY_PPB_POST_09_TEXT', 'A breakdown of the possession layers: expression, eye glow, body line, and the final movement pass.'),
('TXT_KEY_PPB_POST_10_TITLE', 'The Long Cut'),
('TXT_KEY_PPB_POST_10_TEXT', 'This one kept growing. It now includes two transitions, a failed resistance sequence, and an unexpected return to the first body.'),
('TXT_KEY_PPB_POST_11_TITLE', 'The Main Body Returns'),
('TXT_KEY_PPB_POST_11_TEXT', 'The original favorite is back in focus. Baby is stronger, the host is different, and neither seems willing to separate.'),
('TXT_KEY_PPB_POST_12_TITLE', 'Final Form?'),
('TXT_KEY_PPB_POST_12_TEXT', 'The current arc closes with a transformed main host, although “final” may be an optimistic description.'),
('TXT_KEY_PPB_POST_12_NEGATIVE', 'FrameCritic77: “The old host was better and this should have ended two parts ago.”'),

('TXT_KEY_PPB_COMMENT_MORE_01_LABEL', 'Request more Baby'),
('TXT_KEY_PPB_COMMENT_MORE_01_QUOTE', 'It''s not much yet, but he seems to have possession animations! I''m interested in more Baby content.'),
('TXT_KEY_PPB_COMMENT_MORE_02_LABEL', 'Look forward to Part III'),
('TXT_KEY_PPB_COMMENT_MORE_02_QUOTE', 'I look forward to where this goes. A sequel is neat!'),
('TXT_KEY_PPB_COMMENT_MORE_03_LABEL', 'Ask for another sequel'),
('TXT_KEY_PPB_COMMENT_MORE_03_QUOTE', 'A third part already? Neat. You can probably gather that I''m a fan of more Baby content.'),
('TXT_KEY_PPB_COMMENT_MORE_04_LABEL', 'Welcome the next form'),
('TXT_KEY_PPB_COMMENT_MORE_04_QUOTE', 'I''m definitely interested in seeing the next form and where this goes.'),
('TXT_KEY_PPB_COMMENT_MORE_05_LABEL', 'Request the full pool scene'),
('TXT_KEY_PPB_COMMENT_MORE_05_QUOTE', 'This could probably support a longer scene. I would watch more of it.'),
('TXT_KEY_PPB_COMMENT_MORE_06_LABEL', 'Ask for more previews'),
('TXT_KEY_PPB_COMMENT_MORE_06_QUOTE', 'The previews look good. More Baby content is always welcome.'),
('TXT_KEY_PPB_COMMENT_MORE_07_LABEL', 'Ask for the follow-up'),
('TXT_KEY_PPB_COMMENT_MORE_07_QUOTE', 'Hopefully the stronger body gets a full follow-up part.'),
('TXT_KEY_PPB_COMMENT_MORE_08_LABEL', 'Approve the long cut'),
('TXT_KEY_PPB_COMMENT_MORE_08_QUOTE', 'Longer was the right decision. I would not object to another cut.'),
('TXT_KEY_PPB_COMMENT_MORE_09_LABEL', 'Request the next arc'),
('TXT_KEY_PPB_COMMENT_MORE_09_QUOTE', 'A return to the main body and another arc would be neat.'),

('TXT_KEY_PPB_COMMENT_THEORY_01_LABEL', 'Ask about the glowing eyes'),
('TXT_KEY_PPB_COMMENT_THEORY_01_QUOTE', 'Does every character get the eye effect, or only the people Baby actually controls?'),
('TXT_KEY_PPB_COMMENT_THEORY_02_LABEL', 'Ask how the transfer works'),
('TXT_KEY_PPB_COMMENT_THEORY_02_QUOTE', 'How so? Multiple folks are getting possessed throughout?'),
('TXT_KEY_PPB_COMMENT_THEORY_03_LABEL', 'Study the host hierarchy'),
('TXT_KEY_PPB_COMMENT_THEORY_03_QUOTE', 'Is one body actually the main host, or are they all equally controlled?'),
('TXT_KEY_PPB_COMMENT_THEORY_04_LABEL', 'Ask who is in control'),
('TXT_KEY_PPB_COMMENT_THEORY_04_QUOTE', 'Is Baby directing both bodies here, or did the second one inherit the first possession?'),
('TXT_KEY_PPB_COMMENT_THEORY_05_LABEL', 'Compare every eye line'),
('TXT_KEY_PPB_COMMENT_THEORY_05_QUOTE', 'The lines through the eyes seem consistent. Is that the exact moment the host changes?'),
('TXT_KEY_PPB_COMMENT_THEORY_06_LABEL', 'Ask about the preview frames'),
('TXT_KEY_PPB_COMMENT_THEORY_06_QUOTE', 'Are these all from one transition, or are multiple people getting possessed?'),
('TXT_KEY_PPB_COMMENT_THEORY_07_LABEL', 'Study the animation layers'),
('TXT_KEY_PPB_COMMENT_THEORY_07_QUOTE', 'So the expression changes before the eye glow, and the body line comes last?'),
('TXT_KEY_PPB_COMMENT_THEORY_08_LABEL', 'Ask what remained'),
('TXT_KEY_PPB_COMMENT_THEORY_08_QUOTE', 'How much of the original host is still present after the evolution?'),

('TXT_KEY_PPB_COMMENT_HOP_01_LABEL', 'Praise the body hopping'),
('TXT_KEY_PPB_COMMENT_HOP_01_QUOTE', 'Love seeing Baby work his way around, and the lines through the eyes as he moves main bodies!'),
('TXT_KEY_PPB_COMMENT_HOP_02_LABEL', 'Ask for another transfer'),
('TXT_KEY_PPB_COMMENT_HOP_02_QUOTE', 'It would be neat if he jumped into the interrupter next.'),
('TXT_KEY_PPB_COMMENT_HOP_03_LABEL', 'Follow the eye line'),
('TXT_KEY_PPB_COMMENT_HOP_03_QUOTE', 'The eye line makes the body hop much easier to follow. Keep that part.'),
('TXT_KEY_PPB_COMMENT_HOP_04_LABEL', 'Prefer the stronger body'),
('TXT_KEY_PPB_COMMENT_HOP_04_QUOTE', 'The stronger body is a good move, especially if the old one can still come back.'),
('TXT_KEY_PPB_COMMENT_HOP_05_LABEL', 'Approve the double transition'),
('TXT_KEY_PPB_COMMENT_HOP_05_QUOTE', 'Two transitions in one scene works surprisingly well. The return makes it better.'),
('TXT_KEY_PPB_COMMENT_HOP_06_LABEL', 'Reject the word final'),
('TXT_KEY_PPB_COMMENT_HOP_06_QUOTE', 'Final form until Baby sees another useful body, presumably.'),

('TXT_KEY_PPB_COMMENT_MAIN_01_LABEL', 'Suggest the main host'),
('TXT_KEY_PPB_COMMENT_MAIN_01_QUOTE', 'Looking forward to the next part! Hoping this one becomes the main body again as the two evolve in power!'),
('TXT_KEY_PPB_COMMENT_MAIN_02_LABEL', 'Suggest a Super Baby form'),
('TXT_KEY_PPB_COMMENT_MAIN_02_QUOTE', 'Perhaps a Super Baby form? The current host should remain the main body.'),
('TXT_KEY_PPB_COMMENT_MAIN_03_LABEL', 'Choose a favorite host'),
('TXT_KEY_PPB_COMMENT_MAIN_03_QUOTE', 'The third variation looks like the best main host to me.'),
('TXT_KEY_PPB_COMMENT_MAIN_04_LABEL', 'Keep the stronger host'),
('TXT_KEY_PPB_COMMENT_MAIN_04_QUOTE', 'Definitely hope the stronger body remains the main host.'),
('TXT_KEY_PPB_COMMENT_MAIN_05_LABEL', 'Connect the layers to evolution'),
('TXT_KEY_PPB_COMMENT_MAIN_05_QUOTE', 'The layer breakdown makes the shared evolution with the main host much clearer.'),
('TXT_KEY_PPB_COMMENT_MAIN_06_LABEL', 'Welcome the main body back'),
('TXT_KEY_PPB_COMMENT_MAIN_06_QUOTE', 'Good to see the preferred host back as the main body.'),
('TXT_KEY_PPB_COMMENT_MAIN_07_LABEL', 'Keep the final host'),
('TXT_KEY_PPB_COMMENT_MAIN_07_QUOTE', 'Definitely hope this form remains the main host even if the arc continues.'),

('TXT_KEY_PPB_COMMENT_LOYAL_01_LABEL', 'Defend the early preview'),
('TXT_KEY_PPB_COMMENT_LOYAL_01_QUOTE', 'It is an early preview. The subtle effect is clearly the point.'),
('TXT_KEY_PPB_COMMENT_LOYAL_02_LABEL', 'Defend the evolution'),
('TXT_KEY_PPB_COMMENT_LOYAL_02_QUOTE', 'The gradual change is what makes the evolution work.'),
('TXT_KEY_PPB_COMMENT_LOYAL_03_LABEL', 'Answer the negative patron'),
('TXT_KEY_PPB_COMMENT_LOYAL_03_QUOTE', 'You seem to always be disappointed or annoyed. Maybe this is not for you? Everyone else seems to enjoy it.'),
('TXT_KEY_PPB_COMMENT_LOYAL_04_LABEL', 'Defend the process post'),
('TXT_KEY_PPB_COMMENT_LOYAL_04_QUOTE', 'A process breakdown is useful. Not every post needs to be the finished animation.'),
('TXT_KEY_PPB_COMMENT_LOYAL_05_LABEL', 'Defend the longer version'),
('TXT_KEY_PPB_COMMENT_LOYAL_05_QUOTE', 'The longer version gives the possession room to make sense.'),
('TXT_KEY_PPB_COMMENT_LOYAL_06_LABEL', 'Answer the final critic'),
('TXT_KEY_PPB_COMMENT_LOYAL_06_QUOTE', 'If you preferred the old host, that does not make the current work bad. The rest of us are enjoying the arc.');
